### ISSUE TITLE
IOS version

### ISSUE THREAD

**Issue by Alpha11510** [lotusgate/otraku#16]
Sorry for asking this again when some already has asked but will there ever be an ios version. I just switched to an iPhone and using myanilist which never gets updates and has no options, So please make an ios version. There is only 2 apps on app store which are anilist clients, So **please!**

**Comment by lotusgate** [comment]
Well, there is an ios release. But I'm not willing to pay the yearly taxes on the apple app store (as I don't intend to make any money with this project anyway), so the app must be installed through AltStore. With each Github release I include the latest .ipa files. I know that's a little inconvenient and I understand if you don't want to use the app that way, but this is the current solution, sorry.

**Comment by Alpha11510** [comment]
> Well, there is an ios release. But I'm not willing to pay the yearly taxes on the apple app store (as I don't intend to make any money with this project anyway), so the app must be installed through AltStore. With each Github release I include the latest .ipa files. I know that's a little inconvenient and I understand if you don't want to use the app that way, but this is the current solution, sorry.

Okay I will try
