### ISSUE TITLE
F-droid when?

### ISSUE THREAD

**Issue by rihaq** [lotusgate/otraku#18]
And thanks for this awesome app

**Comment by lotusgate** [comment]
I've seen requests for f-droid. I keep it in mind, but for now, I'm prioritising other things (sorry). Still the latest apk files are uploaded with each Github release, so currently this is where non google play users can get the app.
Also, glad you're enjoying the app :)

**Comment by rollingmoai** [comment]
Perhaps on the IzzyOnDroid repo:
https://gitlab.com/IzzyOnDroid/repo/-/issues/297
