### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by Itachisann** [lotusgate/otraku#24]
I found this problem, if it can be solved quickly .. Notifications of new episode releases/airing and activity do not arrive unless you have the app open or in the background

**Comment by lotusgate** [comment]
Usually, the case is that you have battery optimisation turned on for Otraku. Go into settings -> apps -> Otraku and search for something like "battery" or "optimisations" and try disabling it. Otherwise, I believe the notifications should work ok.
