### ISSUE TITLE
Increment lag

### ISSUE THREAD

**Issue by Itachisann** [lotusgate/otraku#25]
When I am on the anime / manga screen and I click the "+" to increase the progress cause lag and the operation is very slow 
![IMG_20220206_042927_340](https://user-images.githubusercontent.com/88840797/152666702-fea7108d-4dec-459f-985a-bbfd1ec52005.jpg)

**Comment by lotusgate** [comment]
When you press the button, the app sends a request to AniList and when it's done, it updates locally. So the speed depends on your internet connection.
If you're talking about another type of lag, please elaborate, so I could look into it.

**Comment by Itachisann** [comment]
I mean the lag of the app, not due to connection, this delay and lag in the increment

https://user-images.githubusercontent.com/88840797/152679321-b64bd634-11fe-4490-943d-33441185a370.mp4

**Comment by lotusgate** [comment]
The number incrementing a second after the tap? It waits for the AniList update request to finish and then changes the number. I could make it so the number would be modified immediately, but I don't want people to be misled, if the AniList update fails for some reason. Though that may end up being the more user-friendly solution 🤔

**Comment by Itachisann** [comment]
Maybe you could do that the number changes instantly, and then in async the app sends the query to anilist?

**Comment by Itachisann** [comment]
Also because if a person has to increase by 20 episodes for example, if he does it quickly it doesn't work and increases 1 episode at a time. So maybe for a 20 second operation it takes you 1 minute

**Comment by lotusgate** [comment]
> if a person has to increase by 20 episodes for example

Um, it's better not to do that through the increment button. AniList has restricted the number of requests per minute for third-party apps. I think it was around 90 requests per minute, so it's typically not that easy to hit, but they also had burst limits and such. I would suggest just holding on the tile to open the editing sheet and do it from there.

> Maybe you could do that the number changes instantly

Yeah, this may be for the better.

**Comment by Itachisann** [comment]
Perfect, thank you very much

**Comment by lotusgate** [comment]
Closing the issues, as this should be working now.
