### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by Alpha11510** [lotusgate/otraku#29]
Hi, I recently installed otraku on my iPhone using AltStore as you suggested and it is so great. I am so excited and happy to use it-It took so long to install because I didn't have a Mac but now I do also on my pc there wasn't a usb 3 cable 😭😢)

So here are the problems-
- [ ] Option to see average score in your anime/manga list currently I can only see my personal score 
EXAMPLE- Let's say I rated FMAB a 10 and it's a 9 by the community then it should be at the top or like second 

- [ ] Option to type messages within the application like the application like in this picture there's no option 
![image](https://user-images.githubusercontent.com/94781213/163001219-cf89e5d0-0bfe-4aed-a2a0-559c52eeab47.png)

Thanks so much for making this application if sometime I would be able to donate you(I am a student high school so yk) I will definitely do it.

Don't stop with your amazing work ❤️()

**Comment by lotusgate** [comment]
Thank you ^^

1. I try to gather only the most necessary data in the media collections, as fetching them is already slow and showing too much details on the tiles may make them look cluttered. So sorry, but I won't be implementing this for now.
2. Commenting is definitely planned.

I'm glad you managed to deal with the cables and such 😅

**Comment by Alpha11510** [comment]
> Thank you ^^
> 
> 
> 
> 1. I try to gather only the most necessary data in the media collections, as fetching them is already slow and showing too much details on the tiles may make them look cluttered. So sorry, but I won't be implementing this for now.
> 
> 2. Commenting is definitely planned.
> 
> 
> 
> I'm glad you managed to deal with the cables and such 😅

Thanks 🙃
I figured something too that in the main page(explore) you can see by score so that was the main necessity2
2.yay!! I thought it was somewhere and I couldn't find it 😅

**Comment by lotusgate** [comment]
The progress section shows everything in your watching/reading lists by splitting it into 4 categories:
- anime that you're watching and is currently airing
- anime that you're watching and is *not* currently airing
- manga that you're reading and is currently releasing
- manga that you're reading and is *not* currently releasing

**Comment by Alpha11510** [comment]
> The progress section shows everything in your watching/reading lists by splitting it into 4 categories:
> 
> - anime that you're watching and is currently airing
> 
> - anime that you're watching and is *not* currently airing
> 
> - manga that you're reading and is currently releasing
> 
> - manga that you're reading and is *not* currently releasing
> 
> 
> 
> You don't have anything in your watching/reading lists currently, right? Because if you have and it's not shown here - this is a bug 😶

I am not watching anything I am rewatching uhh Tokyo ghoul
That's a nice feature 🤩
