### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Itachisann** [lotusgate/otraku#32]
When is it possible to insert a translation? Specifically of the description or information received from AniList?

**Comment by lotusgate** [comment]
I can't give you an ETA, sorry. I have to focus on other things like optimising internet usage (it's pretty heavy currently, but I have an idea of how to fix it), implementing some essential AniList features (like commenting) and improving behind the scenes stuff (like state management).

As a side note: I will close this issue, as there's [a similar one](https://github.com/lotusgate/otraku/issues/17).
