### ISSUE TITLE
Display hidden anime in Progress Tab.

### ISSUE THREAD

**Issue by yash-278** [lotusgate/otraku#36]
Currently the titles that are Hidden in Status lists aren't showing in the Progress tab in app.

For me, I have created custom lists and Hide my anime so that it doesn't show duplicate entry in Anilist default lists. But then it's not shown in app's Progress tab, and it's completely empty all the time.

It'll help if you'll allow Hidden anime to show in Progress tab 😅

**Comment by lotusgate** [comment]
It looks like the way AniList's API is handling this type of request doesn't take into account hidden entries.
The workarounds that I'm coming up with will be impractical and hard to manage, so I don't think this is accomplishable, sorry.

**Comment by yash-278** [comment]
No, actually they show up on the Homepage sections on AL site, try it out yourself sometime too.

Also if it's not accomplishable, then fine, No worries.
I can always go to my lists on other tab.

**Comment by lotusgate** [comment]
Huh... the querries are similar, so I don't know why it doesn't work in Otraku then. I'm probably missing something.
I will get back to this issue in the future.

**Comment by yash-278** [comment]
Progress Tab works as intended now 🎉👍🏻
