### ISSUE TITLE
Feat: Theme previews in settings page.

### ISSUE THREAD

**Issue by Curstantine** [lotusgate/otraku#43]
Having previews for the themes will be quite nice.

![Screenshot_20220727-191851_Otraku-dev](https://user-images.githubusercontent.com/69104500/181263734-e68e9399-e6db-4b1f-b1f1-af479948bd27.jpg)

**Comment by lotusgate** [comment]
I will probably add it in the same update that bundles dynamic material theming. Not sure when that will be, but _not too far off™_

**Comment by Curstantine** [comment]
Ah I was late, I'm going to add the PR now.
