### ISSUE TITLE
Release Order List.

### ISSUE THREAD

**Issue by Devanshu19** [lotusgate/otraku#45]
Currently, the release order list is a chain of Prequels and Sequels. Its hard to find any movie or something in that nested list. 

Animixplay Website does this thing better where release order list is same for every season/movie of the series and all the seasons/movies are listed there. 

Current Situation: ![Screenshot_2022-07-29-11-51-45-43.jpg](https://user-images.githubusercontent.com/66104268/181695896-9f153fa6-f60c-412f-bc4d-83c190e574fb.jpg)

Need to go through all those linked prequels and Sequels to find a particular season/movie in the series.

Desirable Situation: ![Screenshot_2022-07-29-11-51-14-65.jpg](https://user-images.githubusercontent.com/66104268/181696172-10e299a6-cd72-4192-802a-b1f8636e707c.jpg)

List is same of every season in the series which provides full details of the release order at one place.

**Comment by Rollzz** [comment]
I too would like the information provided in one single screen instead of several windows that you just go thru in order to find the season/movie

**Comment by lotusgate** [comment]
I'm afraid there's nothing I can do about this. I'm fetching all relations of a media from AniList and this is all it gives me. Their API just doesn't support what you want; even the site works like what you see on the app.
