### ISSUE TITLE
Gone from Play store?

### ISSUE THREAD

**Issue by DillFrescott** [lotusgate/otraku#52]
It couldnt update, so I clicked on the app and its completely gone from the Play store...

**Comment by lotusgate** [comment]
I temporarely paused the app release as a last-minute problematic bug was
found. I resumed the release just now, but it may take time for the app to
be enabled again. Note that the bug-fixing update is currently under review
from the Play team, so maybe wait a few hours to make sure the fixed
version is out.

**Comment by DillFrescott** [comment]
Ohh gotcha! Thanks for letting me know!
