### ISSUE TITLE
cant login

### ISSUE THREAD

**Issue by lapushkamadre** [lotusgate/otraku#53]
after the recent update, i cant login. i logged in through the anilist website and it dosent redirect me anywhere, going back to the app its just a loading screen

**Comment by lotusgate** [comment]
First time I hear about this. What browser are you using to log in?

**Comment by lapushkamadre** [comment]
vivaldi

**Comment by lotusgate** [comment]
could you try logging in through chrome or firefox?

**Comment by lapushkamadre** [comment]
yeah it works with chrome thanks

**Comment by lotusgate** [comment]
I don't know why it doesn't work with aome browsers. I will perform some changes in the deep linking someday and we will see if it gets fixed then
