### ISSUE TITLE
Bad State: Too many requests 

### ISSUE THREAD

**Issue by Kitsunejasutin** [lotusgate/otraku#59]
This started last week where whenever I load my list or refresh my timeline, it shows this bad state and blocking me from getting any data from loading. I'm not sure if this problem is assessed on apl or Anilist API. If there's any information that is needed let me know.

Basic Specs:
Model : Redmi Note 8
Android Version 13![Screenshot_20221115-210957.png](https://user-images.githubusercontent.com/73803767/201928455-ad2480ce-27bf-45f7-93ca-25032790c263.png)

**Comment by lotusgate** [comment]
Hello, this is a temporary restriction placed by AniList.
I have explained it in this issue https://github.com/lotusgate/otraku/issues/58
(I shouldn't have closed it)

**Comment by Kitsunejasutin** [comment]
I see, thanks for clearing out. Will close this now
