### ISSUE TITLE
Entries

### ISSUE THREAD

**Issue by AhmedElshwadfy** [lotusgate/otraku#60]
When I add some anime episodes and add them as completed It selects all episodes of that anime for example if I marked 5 episodes of an anime of 12 episodes all of them will be chosen but that doesn't happen in the site.

**Comment by AhmedElshwadfy** [comment]
![C218F8CC-B227-47FA-A899-6510D075510C](https://user-images.githubusercontent.com/86772939/201949347-902a876a-1b11-4bbb-a661-724c95f168e7.png)

Here the show status is completed and episode progress is 9 but when i try to do that in the app the show progress will be 26 ( total episodes number of that anime)  not 9.

**Comment by AhmedElshwadfy** [comment]
So i checked it again in the site from my phone not from the pc (the one in my screenshot) and all episodes are checked as completed like what you said, honestly i don't know why it's different from pc .

**Comment by lotusgate** [comment]
I don't know what caused this difference for you. Either way, this is something the app leaves AL to handle, so there's nothing I can do about it.
