### ISSUE TITLE
Notifications Section Blank

### ISSUE THREAD

**Issue by YouSummoner** [lotusgate/otraku#61]
For some reason, the notification settings I'm the app are blank...![Screenshot_20221116-201345_Otraku.png](https://user-images.githubusercontent.com/107224555/202211295-5d05d997-65de-46d3-8a9a-0112d5548bb3.png)

**Comment by lotusgate** [comment]
Hello. First, can you confirm that you are on version 1.2.1+5 (on the last tab of the settings)? Second, can you check whether if you open the app, wait a bit and then open settings, the notifications stay this way? Third, AL had some issues  recently (which may have caused "too many requests" popups), it's possible that the app failed to load settings 🤔. And lastly, and this may sound weird, can you check if the notification settings appear on the AL site? It just so happens that the api notifications can easily break if a script/app/extension mishandles certain things and this may have broken your notifocations.

**Comment by YouSummoner** [comment]
Yeah I'm on the latest version, and notification settings for appear on the Anilist site.
But, dunno I don't think the in-app settings could be affected because of Anilist server issues...
I did check on another client, AniLib and it's settings are working fine...

**Comment by lotusgate** [comment]
Did youbtry waiting a bit before opening settings? I will look into it, to see if I will find the issue before the next update

**Comment by YouSummoner** [comment]
Yeah I did try waiting before opening the settings. Still blank.

**Comment by lotusgate** [comment]
Ok, I will look into it

**Comment by YouSummoner** [comment]
Ok found a solution, I used a client (AniLib) that was still showing the notification settings in it's app, and tried toggling the settings from there. That enabled all the blank options on both the AL website and otraku😜.
