### ISSUE TITLE
Compact grid in collections

### ISSUE THREAD

**Issue by Tendodeku** [lotusgate/otraku#65]
I'll love the ability to change the list view for manga and anime to grid. Make it look just like it does on the progress tab but maybe with score visible as well. Thanks
![Screenshot_20221213-111457_Otraku](https://user-images.githubusercontent.com/96587950/207400115-6d76e3d2-096b-4f68-818f-42649931612b.jpg)

**Comment by lotusgate** [comment]
This is planned, but it's not the most pressing thing, so I can't give you an e.t.a of when I will implement it. On a sidenote, the list in collections acts like a grid if your screen is big enough or if you are in landscape mode, but yeah I get what you want.
By the way, in the upcoming update the progress tab will get removed and instead collections will only load your current/repeated media as a preview. So you will be missing this compact grid for a while, sorry 😅

**Comment by Tendodeku** [comment]
Oh damn, the progress tab will be missed. Guess I'll manage the landscape mode grid for the mean time
