### ISSUE TITLE
expand

### ISSUE THREAD

**Issue by jiwxn** [lotusgate/otraku#68]
![Screenshot_20221220-144947_Otraku](https://user-images.githubusercontent.com/118154420/208732917-6a0ec6af-aa67-4d30-8e40-7ed57a2e54e4.jpg)

hello is there any way I can remove this "expand" and leave it the way it was before? sorry to bother you...

**Comment by lotusgate** [comment]
Hello,
You can't get the progress tab back, but you can disable collection previews in the settings (so a collection will load at once, as it was before).
The progress section wasn't very justified as collections were loading more of the same data essentially, so I merged the 2 things together (there were some other intricacies involved in this decision). I have plans to reimplement the card grid with big images that was in the progress tab, but not the tab itself.

**Comment by jiwxn** [comment]
> Hello, You can't get the progress tab back, but you can disable collection previews in the settings (so a collection will load at once, as it was before). The progress section wasn't very justified as collections were loading more of the same data essentially, so I merged the 2 things together (there were some other intricacies involved in this decision). I have plans to reimplement the card grid with big images that was in the progress tab, but not the tab itself.

thank you, it's back to normal :D
