### ISSUE TITLE
[Feature Request] Filtering out self in Feed

### ISSUE THREAD

**Issue by Amejonah1200** [lotusgate/otraku#69]
Hello,
as I'm someone who reads a lot, I would like to be able to see only others in my (personal) Feed, so I can focus on what my follows are doing, otherwise it gets really spammy.

**Comment by lotusgate** [comment]
AniList shows you activities in following/global feed, so I thought I would too. But now that you mention it, there really isn't much of a utility to that 🤔.
I will think about this.

**Comment by Amejonah1200** [comment]
Well, adding an *option* in the filter drop-up for that would suffice. No need to remove it entirely.

**Comment by lotusgate** [comment]
Yeaaah, I feel like I've been adding a lot of options and toggles recently; I don't want to make the app too cluttered with choices. Maybe I could completely remove your activities from the feed and if a lot of people complain, then I will add a filter toggle. We will see.

**Comment by TheFeelTrain** [comment]
I guess I will start the complaining. I was looking through the settings for this and couldn't find it so ended up coming here. I would prefer it to match the feed on the website. It feels really weird for them to be different and I like seeing my own activites.

**Comment by Amejonah1200** [comment]
Fortunately for you, there is now a setting in the filter selection:
![image](https://github.com/lotusgate/otraku/assets/50181314/fb7260a5-f214-41d2-86f5-7cb5ba3ede10)

**Comment by TheFeelTrain** [comment]
Oh wow I completely missed that. Thanks!
