### ISSUE TITLE
[Feature Request] Delay notification for episode aired

### ISSUE THREAD

**Issue by Matth7878** [lotusgate/otraku#70]
Otraku have a nice feature to notify you when an episode for an anime you're watching is aired. But if you're watching anime in simulcast on a streaming service then episodes are usually available only 2 hours later.
It would be nice to be able to set a delay for episode aired to get notified only when episodes are really available.

**Comment by lotusgate** [comment]
Otraku is just a third-party client for AniList and I can't do more with the notifications, than the site does. Otraku is simply rechannelling notifications from AniList, so unless they implement such a feature, I can't help you.
