### ISSUE TITLE
[Feature Request] Unified Push Support

### ISSUE THREAD

**Issue by Sorunome** [lotusgate/otraku#71]
It would be cool if this app could support [Unified Push](https://unifiedpush.org/). That is basically an open protocol for push notifications, making so that apps can get push notifs without google services and without going via google. It is really amazing for privacy, and it would be cool if that could be added!

**Comment by lotusgate** [comment]
I haven't heard of that, but if I'm understanding it correctly, it's not something that is related to Otraku.
The AniList servers don't push any notifications, nor have I set up a proxy server to channel notifications. The app just occasionally runs in the background and fetches the batch of unread notifications from AL. I don't think this goes through google? (Correct me if I'm misunderstanding Unified Push)

**Comment by Sorunome** [comment]
Ah ok, I wasn't too aware of its internal functioning.

As you understood correctly, Unified Push is about receiving push notifications in a FOSS way, but as Otraku, as you said, uses pull notifications then it isn't needed. Thank you for your time, and the app seems great so far!
