### ISSUE TITLE
[Feature Request] add read all notification button at notification page.

### ISSUE THREAD

**Issue by soymadip** [lotusgate/otraku#73]
As of now the notification page doesn't have any read notifications button. 
We have to pull down and refresh to dismiss the notifications. 
![Screenshot_2023-02-22-09-29-04-48_b8ac2621a5fc4ab25de08be2f76e4f01](https://user-images.githubusercontent.com/84225810/220518745-7502080f-70da-4f9a-923d-cac2ccf2945b.jpg)

- Now if a button is added at the top right corner, we can press that butter to dismiss the notifications instead of refreshing.

**Comment by lotusgate** [comment]
What do you mean dismiss? The notifications work the same way they do on AniList - when you open the notification page you see all of them in chronological order; the new ones are marked, but the AL server will automatically decide you've read all of them.

**Comment by soymadip** [comment]
> What do you mean dismiss? The notifications work the same way they do on AniList - when you open the notification page you see all of them in chronological order; the new ones are marked, but the AL server will automatically decide you've read all of them.

Oh, sorry I missed a word. I was saying about unread notifications. 
Anilist has a button to mark them as read.
![IMG_20230222_204556](https://user-images.githubusercontent.com/84225810/220666624-3f1ea6d2-be38-4f65-a096-104ba3f073b2.jpg)

**Comment by soymadip** [comment]
Sorry, just noticed app automatically mark as read them. 
I am really sorry.
