### ISSUE TITLE
Search history / image cache

### ISSUE THREAD

**Issue by AhmedElshwadfy** [lotusgate/otraku#74]
Please consider adding history feature to search tab and image cache to save data.

**Comment by lotusgate** [comment]
I'm adding image caching for the next update, but I probably won't implement the search history. We've talked about this on the discord server and iirc the consensus was that it's more useful to directly see the search results, instead of a list with old searches.

**Comment by AhmedElshwadfy** [comment]
Well you have a good point and it's not that important anyway,thanks for the great work in the app too.

**Comment by lotusgate** [comment]
Great, I will close this, when I release the next update.
