### ISSUE TITLE
F-Droid "Incompatable Device" and "Could not Install due to unknown reason"

### ISSUE THREAD

**Issue by rktfier** [lotusgate/otraku#82]
Hello there, i was just browsing the F-Droid repositories today and i noticed this app. I have been using the Play version for around a year now, so i went ahead and uninstalled it, but when i tried to download the F-Droid version i was warned with "This app is incompatible with your device" and when i tried to proceed, it failed just after the package installer due to "Unknown Reason". I'm using Android 13 and i noticed that the Play Store version is 1.2.4 also. What could be the reason for this issue?

**Comment by lotusgate** [comment]
Hello, Otraku was registered on F-Droid by another person and I don't use the store personally, so I'm afraid I can't help you much. And yes, the version on the Play store is 1.2.4+1, like the latest Github release.
Not uninstalling the Play version, before installing the other one may cause problems, but I don't know if that's your case.

**Comment by rktfier** [comment]
I think the version on F-Droid is outdated, as it shows 1.2.4 instead of 1.2.4+1. It could be good to nudge the person who uploaded it about this. Thank you for your response, it would be good to see more cool apps like this at F-Droid.
