### ISSUE TITLE
Add missing fields to list editor

### ISSUE THREAD

**Issue by crxssed7** [lotusgate/otraku#84]
I noticed some fields are missing from the list editor. In particular the "priority" field. Maybe an option to add/remove fields?

![Screenshot_20230617_195022_Otraku](https://github.com/lotusgate/otraku/assets/48864420/22439a39-a78b-4124-bf52-d1abfbe5ec20)

**Comment by lotusgate** [comment]
AniList doesn't use the priority field. It's deprecated as far as I know.
